// <auto-generated />
using System;
using Day2_MvcCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day2_MvcCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608070924_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Day2_MvcCore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#3b82f6",
                            Icon = "💼",
                            Name = "Công việc"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#8b5cf6",
                            Icon = "🎓",
                            Name = "Học tập"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#10b981",
                            Icon = "🏠",
                            Name = "Cá nhân"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#ef4444",
                            Icon = "🔥",
                            Name = "Khẩn cấp"
                        });
                });

            modelBuilder.Entity("Day2_MvcCore.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đọc tài liệu về luồng dữ liệu giữa Model, View và Controller.",
                            DueDate = new DateTime(2026, 6, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            Priority = 2,
                            Title = "Tìm hiểu về MVC là gì?"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cài đặt SQLite, tạo AppDbContext, chạy Migration để tạo DB.",
                            DueDate = new DateTime(2026, 6, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Cấu hình Entity Framework Core"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mua rau quả, sữa và thức ăn cho tuần tới.",
                            DueDate = new DateTime(2026, 6, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Priority = 0,
                            Title = "Mua sắm nhu yếu phẩm"
                        });
                });

            modelBuilder.Entity("Day2_MvcCore.Models.TodoItem", b =>
                {
                    b.HasOne("Day2_MvcCore.Models.Category", "Category")
                        .WithMany("TodoItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Day2_MvcCore.Models.Category", b =>
                {
                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
